version: '3.5'

services:
  web:
    container_name: web
    restart: always
    build: ./web
    command: gunicorn backend.wsgi:application --bind :80 --preload --workers 3
    volumes:
      - static_volume:/home/app/src/static
      - media_volume:/home/app/src/media
    expose:
      - 80
    env_file: ./web/.env
    depends_on:
      - db
    links:
      - db
  nginx:
    container_name: nginx
    restart: always
    build: ./nginx
    volumes:
      - static_volume:/home/app/src/static
      - media_volume:/home/app/src/media
    ports:
      - 80:80
    env_file: ./web/.env
    depends_on:
      - web
  db:
    container_name: db
    restart: always
    image: mysql
    ports:
      - 3306
    env_file: ./web/.env
    healthcheck:
      test: ["CMD", "mysqladmin", "-u$MYSQL_USER", "-p$MYSQL_PASSWORD",  "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
  static_volume:
  media_volume: