# Generated by Django 2.2.6 on 2019-11-02 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        ('register', '0004_auto_20191031_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='events',
            field=models.ManyToManyField(related_name='users', to='events.Event'),
        ),
        migrations.AlterField(
            model_name='jobplace',
            name='name',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='jobposition',
            name='name',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
