# Generated by Django 2.2.6 on 2019-11-12 06:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0005_auto_20191102_1500'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='additionaluserinfo',
            options={'verbose_name': 'Дополнительная информация о пользователе', 'verbose_name_plural': 'Дополнительная информация о пользователе'},
        ),
        migrations.AlterModelOptions(
            name='jobplace',
            options={'verbose_name': 'Место работы', 'verbose_name_plural': 'Места работы'},
        ),
        migrations.AlterModelOptions(
            name='jobposition',
            options={'verbose_name': 'Должность', 'verbose_name_plural': 'Должности'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterField(
            model_name='additionaluserinfo',
            name='about',
            field=models.TextField(blank=True, max_length=500, verbose_name='Обо мне'),
        ),
        migrations.AlterField(
            model_name='additionaluserinfo',
            name='address',
            field=models.CharField(blank=True, max_length=120, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='additionaluserinfo',
            name='city',
            field=models.CharField(max_length=30, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='additionaluserinfo',
            name='country',
            field=models.CharField(default='Россия', max_length=30, verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='additionaluserinfo',
            name='mail_index',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Почтовый индекс'),
        ),
        migrations.AlterField(
            model_name='additionaluserinfo',
            name='phone',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='additionaluserinfo',
            name='region',
            field=models.CharField(max_length=50, verbose_name='Регион'),
        ),
        migrations.AlterField(
            model_name='additionaluserinfo',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='additional_info', serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='jobplace',
            name='name',
            field=models.CharField(max_length=150, unique=True, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='jobposition',
            name='name',
            field=models.CharField(max_length=150, unique=True, verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=70, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='user',
            name='events',
            field=models.ManyToManyField(blank=True, related_name='users', to='events.Event', verbose_name='Мероприятия'),
        ),
        migrations.AlterField(
            model_name='user',
            name='experience',
            field=models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='Стаж'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=30, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='job_place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='users', to='register.JobPlace', verbose_name='Место работы'),
        ),
        migrations.AlterField(
            model_name='user',
            name='job_position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='users', to='register.JobPosition', verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=30, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='user',
            name='patronymic',
            field=models.CharField(max_length=30, verbose_name='Отчество'),
        ),
    ]
