# Generated by Django 2.2.6 on 2019-11-25 14:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0007_auto_20191119_0004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionaluserinfo',
            name='mail_index',
            field=models.CharField(blank=True, max_length=6, validators=[django.core.validators.RegexValidator(message='Почтовый индекс должен быть в формате: 123456', regex='^\\d{5,6}$')], verbose_name='Почтовый индекс'),
        ),
        migrations.AlterField(
            model_name='additionaluserinfo',
            name='phone',
            field=models.CharField(blank=True, max_length=11, null=True, validators=[django.core.validators.RegexValidator(message='Телефон должен быть в формате: 12345678910', regex='^\\d{6,11}$')], verbose_name='Телефон'),
        ),
    ]
