# Generated by Django 2.2.6 on 2019-11-26 06:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0008_auto_20191125_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionaluserinfo',
            name='phone',
            field=models.CharField(blank=True, max_length=11, validators=[django.core.validators.RegexValidator(message='Телефон должен быть в формате: 12345678910', regex='^\\d{6,11}$')], verbose_name='Телефон'),
        ),
    ]
