# Generated by Django 2.2.6 on 2019-11-26 06:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0009_auto_20191126_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionaluserinfo',
            name='about',
            field=models.TextField(max_length=500, verbose_name='Обо мне'),
        ),
        migrations.AlterField(
            model_name='additionaluserinfo',
            name='address',
            field=models.CharField(max_length=120, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='additionaluserinfo',
            name='mail_index',
            field=models.CharField(max_length=6, validators=[django.core.validators.RegexValidator(message='Почтовый индекс должен быть в формате: 123456', regex='^\\d{5,6}$')], verbose_name='Почтовый индекс'),
        ),
        migrations.AlterField(
            model_name='additionaluserinfo',
            name='phone',
            field=models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message='Телефон должен быть в формате: 12345678910', regex='^\\d{6,11}$')], verbose_name='Телефон'),
        ),
    ]
