# Generated by Django 3.0.1 on 2019-12-31 21:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0011_user_email_confirmed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionaluserinfo',
            name='city',
            field=models.CharField(max_length=30, validators=[django.core.validators.RegexValidator(message='Это поле может содержать только заглавные и строчные буквы', regex='[а-яё]|[А-ЯЁ]')], verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='additionaluserinfo',
            name='country',
            field=models.CharField(default='Россия', max_length=30, validators=[django.core.validators.RegexValidator(message='Это поле может содержать только заглавные и строчные буквы', regex='[а-яё]|[А-ЯЁ]')], verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='additionaluserinfo',
            name='mail_index',
            field=models.CharField(max_length=6, validators=[django.core.validators.RegexValidator(message='Почтовый индекс должен быть в формате: 112233', regex='^\\d{5,6}$')], verbose_name='Почтовый индекс'),
        ),
        migrations.AlterField(
            model_name='additionaluserinfo',
            name='phone',
            field=models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message='Телефон должен быть в формате: 89991234567', regex='^\\d{6,11}$')], verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='additionaluserinfo',
            name='region',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='Это поле может содержать только заглавные и строчные буквы', regex='[а-яё]|[А-ЯЁ]')], verbose_name='Регион'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=30, validators=[django.core.validators.RegexValidator(message='Это поле может содержать только заглавные и строчные буквы', regex='[а-яё]|[А-ЯЁ]')], verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=30, validators=[django.core.validators.RegexValidator(message='Это поле может содержать только заглавные и строчные буквы', regex='[а-яё]|[А-ЯЁ]')], verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='user',
            name='patronymic',
            field=models.CharField(blank=True, max_length=30, validators=[django.core.validators.RegexValidator(message='Это поле может содержать только заглавные и строчные буквы', regex='[а-яё]|[А-ЯЁ]')], verbose_name='Отчество'),
        ),
    ]
