# Generated by Django 2.2.6 on 2019-11-12 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'Мероприятие', 'verbose_name_plural': 'Мероприятия'},
        ),
        migrations.AlterModelOptions(
            name='eventdate',
            options={'verbose_name': 'Дата мероприятия', 'verbose_name_plural': 'Даты мероприятий'},
        ),
        migrations.AlterModelOptions(
            name='eventorganizer',
            options={'verbose_name': 'Организатор', 'verbose_name_plural': 'Организаторы'},
        ),
        migrations.AlterModelOptions(
            name='pressrelease',
            options={'verbose_name': 'Пресс релиз', 'verbose_name_plural': 'Пресс релизы'},
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(max_length=150, unique=True, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='event',
            name='organizer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='events.EventOrganizer', verbose_name='Организатор'),
        ),
        migrations.AlterField(
            model_name='eventdate',
            name='end_date',
            field=models.DateField(null=True, verbose_name='Дата окончания'),
        ),
        migrations.AlterField(
            model_name='eventdate',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dates', to='events.Event', verbose_name='Мероприятие'),
        ),
        migrations.AlterField(
            model_name='eventdate',
            name='start_date',
            field=models.DateField(null=True, verbose_name='Дата начала'),
        ),
        migrations.AlterField(
            model_name='eventorganizer',
            name='address',
            field=models.CharField(max_length=120, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='eventorganizer',
            name='name',
            field=models.CharField(max_length=150, unique=True, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='eventorganizer',
            name='phone',
            field=models.CharField(max_length=11, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='pressrelease',
            name='event_date',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, related_name='press_release', serialize=False, to='events.EventDate', verbose_name='Дата мероприятия'),
        ),
        migrations.AlterField(
            model_name='pressrelease',
            name='file',
            field=models.FileField(upload_to='', verbose_name='Файл'),
        ),
    ]
