# Generated by Django 2.2.6 on 2019-11-12 06:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contract',
            options={'verbose_name': 'Договор', 'verbose_name_plural': 'Договоры'},
        ),
        migrations.AlterModelOptions(
            name='document',
            options={'verbose_name': 'Документ', 'verbose_name_plural': 'Документы'},
        ),
        migrations.AlterModelOptions(
            name='documentregulation',
            options={'verbose_name': 'Регламент документа', 'verbose_name_plural': 'Регламенты документов'},
        ),
        migrations.AlterModelOptions(
            name='documenttype',
            options={'verbose_name': 'Вид документа', 'verbose_name_plural': 'Виды документов'},
        ),
        migrations.AlterField(
            model_name='contract',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='document_regulation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='contracts', to='documents.DocumentRegulation', verbose_name='Документ регламент'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='number',
            field=models.CharField(max_length=50, unique=True, verbose_name='Номер'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='documents', to='documents.DocumentType', verbose_name='Вид документа'),
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(upload_to='', verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='document',
            name='number',
            field=models.CharField(max_length=50, unique=True, verbose_name='Номер'),
        ),
        migrations.AlterField(
            model_name='document',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='documentregulation',
            name='document_type',
            field=models.CharField(max_length=150, unique=True, verbose_name='Вид документа'),
        ),
        migrations.AlterField(
            model_name='documenttype',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='document_types', to='events.Event', verbose_name='Мероприятие'),
        ),
        migrations.AlterField(
            model_name='documenttype',
            name='name',
            field=models.CharField(max_length=150, unique=True, verbose_name='Наименование'),
        ),
    ]
