# Generated by Django 2.2.6 on 2019-11-12 07:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_auto_20191112_1145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='date',
        ),
        migrations.AddField(
            model_name='contract',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата завершения'),
        ),
        migrations.AddField(
            model_name='contract',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата заключения'),
        ),
    ]
