# Generated by Django 2.2.6 on 2019-11-12 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_auto_20191112_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='start_date',
            field=models.DateField(auto_now_add=True, verbose_name='Дата заключения'),
        ),
    ]
