# Generated by Django 2.2.6 on 2019-11-12 07:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_auto_20191112_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата заключения'),
        ),
    ]
